source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RxSwiftExtDemo' do
    pod 'RxSwift'
	pod 'RxSwiftExt', :path => '../'
end

target 'RxSwiftExtDemoTests' do
    pod 'RxSwift'
    pod 'RxTests'
	pod 'RxSwiftExt', :path => '../'
end