source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RxSwiftExtDemo' do
    pod 'RxSwift'
	pod 'RxSwiftExt', :path => '../'
end

target 'RxSwiftExtDemoTests' do
    pod 'RxSwift'
    pod 'RxTests'
	pod 'RxSwiftExt', :path => '../'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
        end
    end
end